package com.example.unit.dao;
import com.example.unit.model.UnitEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface UnitEntityMapper {
    //用户登录
    UnitEntity userlogin(@Param("name") String username,@Param("code") String password);

    //注册新用户(方式1)
    int adduser(@Param("name") String username, @Param("code") String password, @Param("address") String age);

    //注册新用户（方式2）
    int adduser1(@Param("name") String username, @Param("code") String password, @Param("address") String age);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit
     *
     * @mbg.generated
     */
    int insert(UnitEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit
     *
     * @mbg.generated
     */
    int insertSelective(UnitEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit
     *
     * @mbg.generated
     */
    UnitEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UnitEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_unit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UnitEntity record);
}